import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

function Section({ title, children }) {
  return (
    <div className="mb-10">
      <h2 className="text-lg font-semibold text-white mb-3">{title}</h2>
      <div className="space-y-3 text-[15px] text-zinc-400 leading-relaxed">{children}</div>
    </div>
  );
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-black text-slate-100 flex flex-col">
      <Navbar />
      <main className="flex-1 w-full max-w-3xl mx-auto px-5 py-16">
        <div className="mb-10">
          <a href="/" className="text-sm text-zinc-600 hover:text-zinc-400 transition">← Back to Declawed</a>
        </div>
        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-sm text-zinc-600 mb-12">Last updated: July 2025</p>

        <div className="mb-10 p-5 rounded-xl border border-amber-500/30 bg-amber-500/5">
          <p className="text-amber-300 font-semibold text-sm mb-1">Important Disclaimer</p>
          <p className="text-sm text-amber-200/70 leading-relaxed">
            Declawed is not a law firm and does not provide legal advice. Outputs generated by this service are for informational purposes only and do not constitute legal counsel. Do not rely on Declawed as a substitute for advice from a qualified attorney. Always consult a licensed legal professional before signing any lease or rental agreement.
          </p>
        </div>

        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using Declawed at declawed.app ("Service"), you agree to be bound by these Terms of Service. If you do not agree, you must not use the Service.
          </p>
          <p>
            We reserve the right to modify these Terms at any time. We will notify users of material changes by updating the "Last updated" date. Continued use after changes constitutes acceptance.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            Declawed is an AI-powered tool that analyzes residential lease and rental agreements to help tenants understand their rights, identify red flags, and navigate key terms. The Service uses Anthropic's Claude AI to generate summaries and analysis.
          </p>
          <p>
            The Service is intended primarily for US and Canadian residential leases. Analysis accuracy may vary for other jurisdictions or document types.
          </p>
        </Section>

        <Section title="3. No Legal Advice">
          <p>
            Declawed does not provide legal advice. Analysis generated by the Service is for general informational purposes only and may not accurately reflect the laws of your jurisdiction. The Service does not create an attorney-client relationship between you and Declawed.
          </p>
          <p>
            You should not take or refrain from taking any action based solely on Declawed's output without first consulting a qualified attorney.
          </p>
        </Section>

        <Section title="4. User Accounts">
          <p>
            You must be 18 years of age or older to create an account. You are responsible for maintaining the security of your account credentials and for all activity that occurs under your account.
          </p>
          <p>
            You agree to provide accurate information when creating an account and to notify us promptly of any unauthorized access.
          </p>
        </Section>

        <Section title="5. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-1.5 pl-2">
            <li>Upload documents containing illegal content</li>
            <li>Attempt to reverse-engineer, scrape, or circumvent subscription limits</li>
            <li>Use the Service to harass, harm, or deceive any person</li>
            <li>Use automated scripts to make excessive API requests</li>
            <li>Misrepresent the Service's outputs as actual legal advice</li>
            <li>Attempt to manipulate the AI to produce harmful or misleading outputs</li>
          </ul>
          <p>Violation of these terms may result in immediate account termination without refund.</p>
        </Section>

        <Section title="6. Subscription and Payment">
          <p>
            Declawed offers a free tier and paid subscription plans ("One Lease", "Pro", and "Unlimited"). Paid plans are billed via Stripe using the pricing displayed on the pricing page at time of purchase.
          </p>
          <p>
            Subscription plans are as described at the time of purchase. We reserve the right to change pricing with reasonable notice. Price changes will not affect already-purchased one-time plans.
          </p>
          <p>
            All payments are processed securely by Stripe. We do not store your payment card details.
          </p>
        </Section>

        <Section title="7. Refunds">
          <p>
            Due to the nature of digital services, all sales are generally final. However, if you experience a technical failure that prevents you from using a paid analysis you purchased, please contact us within 7 days at <span className="text-teal-400">support@declawed.app</span> and we will review your case.
          </p>
        </Section>

        <Section title="8. Intellectual Property">
          <p>
            The Declawed name, logo, design, and codebase are owned by Declawed and protected by applicable intellectual property laws. You may not reproduce, modify, or distribute our content without permission.
          </p>
          <p>
            You retain full ownership of the documents you upload. By uploading documents, you grant us a limited license to process them for the purpose of providing the Service.
          </p>
        </Section>

        <Section title="9. Disclaimer of Warranties">
          <p>
            The Service is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that AI-generated analysis will be accurate or complete.
          </p>
          <p>
            We are not responsible for any decisions you make based on the Service's output.
          </p>
        </Section>

        <Section title="10. Limitation of Liability">
          <p>
            To the maximum extent permitted by law, Declawed shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to loss resulting from reliance on AI-generated analysis.
          </p>
          <p>
            Our total liability to you for any claim arising from the Service shall not exceed the amount you paid us in the 12 months preceding the claim, or $10, whichever is greater.
          </p>
        </Section>

        <Section title="11. Governing Law">
          <p>
            These Terms are governed by the laws of the State of Delaware, USA, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Delaware.
          </p>
        </Section>

        <Section title="12. Termination">
          <p>
            We may suspend or terminate your account at any time for violation of these Terms or for any other reason with or without notice. You may delete your account at any time from the Dashboard or by contacting us.
          </p>
        </Section>

        <Section title="13. Contact">
          <p>
            Questions about these Terms can be directed to <span className="text-teal-400">support@declawed.app</span>.
          </p>
        </Section>
      </main>
      <Footer />
    </div>
  );
}
