import { FileText, AlertTriangle } from 'lucide-react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

function Section({ number, title, children }) {
  return (
    <div className="rounded-2xl border border-white/[0.07] bg-white/[0.02] p-6 hover:border-white/[0.10] transition-colors">
      <h2 className="text-base font-semibold text-white mb-4 flex items-start gap-3">
        <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-600 tabular-nums mt-1 shrink-0 w-5">{number}.</span>
        <span>{title}</span>
      </h2>
      <div className="space-y-3 text-[14.5px] text-zinc-400 leading-relaxed pl-8">{children}</div>
    </div>
  );
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#07070d] text-slate-100 flex flex-col">
      <Navbar />

      {/* Hero */}
      <div className="relative overflow-hidden border-b border-white/[0.06]">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute left-1/2 top-0 -translate-x-1/2 w-[600px] h-[300px] rounded-full bg-blue-500/[0.05] blur-[100px]" />
          <div
            className="absolute inset-0 opacity-[0.25]"
            style={{
              backgroundImage: 'radial-gradient(circle, rgba(255,255,255,0.05) 1px, transparent 1px)',
              backgroundSize: '32px 32px',
              maskImage: 'radial-gradient(ellipse 80% 60% at 50% 0%, #000 20%, transparent 100%)',
              WebkitMaskImage: 'radial-gradient(ellipse 80% 60% at 50% 0%, #000 20%, transparent 100%)',
            }}
          />
        </div>
        <div className="relative z-10 max-w-3xl mx-auto px-5 py-16">
          <a href="/" className="inline-flex items-center gap-1.5 text-[13px] text-zinc-600 hover:text-zinc-300 transition mb-8 group">
            <span className="group-hover:-translate-x-0.5 transition-transform">←</span>
            Back to Declawed
          </a>
          <div className="flex items-center gap-4 mb-5">
            <div className="w-11 h-11 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center shrink-0">
              <FileText className="w-5 h-5 text-blue-400" />
            </div>
            <h1 className="text-3xl md:text-4xl font-bold text-white tracking-tight">Terms of Service</h1>
          </div>
          <p className="text-[13px] text-zinc-600 mb-4">Last updated: March 25, 2026</p>
          <p className="text-zinc-400 leading-relaxed max-w-xl">
            Please read these Terms carefully before using Declawed. By accessing or using our service, you agree to be bound by these Terms.
          </p>
        </div>
      </div>

      <main className="flex-1 w-full max-w-3xl mx-auto px-5 py-12">
        <div className="space-y-3">

          {/* Disclaimer callout */}
          <div className="rounded-2xl border border-amber-500/25 bg-amber-500/[0.05] p-5 flex gap-4">
            <div className="w-9 h-9 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center shrink-0 mt-0.5">
              <AlertTriangle className="w-4 h-4 text-amber-400" />
            </div>
            <div>
              <p className="text-amber-300 font-semibold text-sm mb-1">Important Disclaimer</p>
              <p className="text-[13.5px] text-amber-200/65 leading-relaxed">
                Declawed is not a law firm and does not provide legal advice. Outputs generated by this service are for informational purposes only and do not constitute legal counsel. Always consult a licensed legal professional before signing any lease or rental agreement.
              </p>
            </div>
          </div>

          <Section number="1" title="Acceptance of Terms">
            <p>
              By accessing or using Declawed at declawed.app ("Service"), you agree to be bound by these Terms of Service. If you do not agree, you must not use the Service.
            </p>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of material changes by updating the "Last updated" date. Continued use after changes constitutes acceptance.
            </p>
          </Section>

          <Section number="2" title="Description of Service">
            <p>
              Declawed is an AI-powered tool that analyzes residential lease and rental agreements to help tenants and landlords understand key terms, identify red flags, and navigate their rights. The Service uses Anthropic's Claude AI to generate structured analysis.
            </p>
            <p>
              The Service is intended primarily for US and Canadian residential leases, though it can process leases from other jurisdictions. Analysis accuracy may vary for non-standard document types or highly jurisdiction-specific language.
            </p>
          </Section>

          <Section number="3" title="No Legal Advice">
            <p>
              Declawed does not provide legal advice. Analysis generated by the Service is for general informational purposes only and may not accurately reflect the laws of your jurisdiction. The Service does not create an attorney-client relationship between you and Declawed.
            </p>
            <p>
              You should not take or refrain from taking any action based solely on Declawed's output without first consulting a qualified attorney.
            </p>
          </Section>

          <Section number="4" title="User Accounts">
            <p>
              You must be 18 years of age or older to create an account. You are responsible for maintaining the security of your account credentials and for all activity that occurs under your account.
            </p>
            <p>
              You agree to provide accurate information when creating an account — including your full name — and to notify us promptly of any unauthorized access. You may update your profile information at any time.
            </p>
          </Section>

          <Section number="5" title="Acceptable Use">
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-1.5 pl-2">
              <li>Upload documents containing illegal content</li>
              <li>Attempt to reverse-engineer, scrape, or circumvent subscription limits</li>
              <li>Use the Service to harass, harm, or deceive any person</li>
              <li>Use automated scripts to make excessive API requests</li>
              <li>Misrepresent the Service's outputs as actual legal advice</li>
              <li>Attempt to manipulate the AI to produce harmful or misleading outputs</li>
            </ul>
            <p>Violation of these terms may result in immediate account termination without refund.</p>
          </Section>

          <Section number="6" title="Subscription and Payment">
            <p>
              Declawed offers a free tier (1 analysis) and paid plans: One Lease ($3.99 one-time), Pro ($12/mo, 10 analyses), and Unlimited ($29/mo, unlimited analyses). Paid plans are billed via Stripe at the pricing displayed at time of purchase.
            </p>
            <p>
              Subscription plans are as described at the time of purchase. We reserve the right to change pricing with reasonable notice. Price changes will not affect already-purchased one-time plans.
            </p>
            <p>
              All payments are processed securely by Stripe. We do not store your payment card details.
            </p>
          </Section>

          <Section number="7" title="Refunds">
            <p>
              Due to the nature of digital services, all sales are generally final. However, we offer a 7-day money-back guarantee on all paid plans. If you experience a technical failure or are unsatisfied within 7 days of purchase, contact us at <span className="text-blue-400">support@declawed.app</span> and we will review your case. You can also request a refund directly from your dashboard.
            </p>
          </Section>

          <Section number="8" title="Intellectual Property">
            <p>
              The Declawed name, logo, design, and codebase are owned by Declawed and protected by applicable intellectual property laws. You may not reproduce, modify, or distribute our content without permission.
            </p>
            <p>
              You retain full ownership of the documents you upload. By uploading documents, you grant us a limited license to process them for the purpose of providing the Service.
            </p>
          </Section>

          <Section number="9" title="Disclaimer of Warranties">
            <p>
              The Service is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that AI-generated analysis will be accurate or complete.
            </p>
            <p>
              We are not responsible for any decisions you make based on the Service's output.
            </p>
          </Section>

          <Section number="10" title="Limitation of Liability">
            <p>
              To the maximum extent permitted by law, Declawed shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to loss resulting from reliance on AI-generated analysis.
            </p>
            <p>
              Our total liability to you for any claim arising from the Service shall not exceed the amount you paid us in the 12 months preceding the claim, or $10, whichever is greater.
            </p>
          </Section>

          <Section number="11" title="Governing Law">
            <p>
              These Terms are governed by the laws of the State of Delaware, USA, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Delaware.
            </p>
          </Section>

          <Section number="12" title="Termination">
            <p>
              We may suspend or terminate your account at any time for violation of these Terms or for any other reason with or without notice. You may delete your account at any time from the Dashboard or by contacting us.
            </p>
          </Section>

          <Section number="13" title="Contact">
            <p>
              Questions about these Terms can be directed to <span className="text-blue-400">support@declawed.app</span>.
            </p>
          </Section>

        </div>
      </main>
      <Footer />
    </div>
  );
}
